### ISSUE TITLE
Permalink (when it works) > deel

### ISSUE THREAD

**Issue by kgish** [kgish/discourse-annotator-plugin#37]

**Comment by Socioneers** [comment]
Permalink not working in test machine should (only be in fold out)

**Comment by kgish** [comment]
Did you rebuild the test server since I committed the code?

Should display 'deel' now instead of 'permalink'

**Comment by Socioneers** [comment]
Hi Kiffin,

I don’t see those menu items in the test version.

Raoul
---

+31(0)6 4 66 28 28 3
@socioneers
http://socioneers.com


This email is hosted sustainably.
Important Note: Any unauthorised copying, disclosure or distribution of the material inclosed is strictly forbidden. The Socioneers are registered at the Dutch Chamber of Commerce under number: KVK 09178876

**Comment by Socioneers** [comment]
Not fixed, clicking it gives a grey screen and annotations disappear

<img width="1399" alt="screen shot 2016-09-27 at 14 31 52" src="https://cloud.githubusercontent.com/assets/11832800/18873448/cb3fca12-84bf-11e6-9cf4-005e6984b4b6.png">

**Comment by Socioneers** [comment]
popup copy link
